server.port: 8089

spring.mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER
spring.mvc.throw-exception-if-no-handler-found: true
spring.resources.add-mappings: false

# Demo - generic external call
services.demo.uri.internal: http://gaia-x.demo.local:8081/demo
services.lcm.uri.internal: http://gaia-x.demo.local:8081/demo

spring.main.allow-circular-references: true

# KEYCLOAK-------------------------------------------
keycloak.auth-server-url: ${KC_URL}
keycloak.realm: ${KC_REALM}
keycloak.resource: ${KC_RESOURCE}
keycloak.public-client: true
keycloak.bearer-only: true

keycloak.principal-attribute: preferred_username

check-keycloak-token: true
#----------------------------------------------------

springfox:
  documentation:
    swaggerUi:
      baseUrl: /api/dashboard
    openApi:
      v3:
        path: /api/dashboard/v3/api-docs
    swagger:
      v2:
        path: /api/dashboard/v2/api-docs
---
spring.config.activate.on-profile: mesh
server.port: 80
server.shutdown: graceful
spring.lifecycle.timeout-per-shutdown-phase: 10s
management.endpoint.health.probes.enabled: true
management.endpoints.web.exposure.include: "*"
management.server.port: 4004

services.demo.uri.internal: http://demo/demo
services.lcm.uri.internal: http://demo/demo